"""Crawfish — agents for bulk work over your data.

``Source → Batch (fan-out) → Aggregator (reduce) → Router (branch) → Sink``,
authored as directories and run locally via ``claude -p``.

This module re-exports the stable public surface. As primitives land (M1–M5) they
are added here, each placed in its stability tier.
"""

from __future__ import annotations

from crawfish.anomaly import (
    AnomalyEngine,
    AnomalyRule,
    BudgetApproachingRule,
    CostSpikeRule,
    EmissionFloodRule,
    FailureRateRule,
    Firing,
    Response,
    StuckRunRule,
    read_and_guard,
)
from crawfish.artifacts import (
    ArtifactRef,
    ArtifactStore,
    LocalArtifactStore,
    offload_if_large,
)
from crawfish.batch import Anomaly, Batch, Task
from crawfish.build import BuildPlan, generate_containerfile, plan_build, write_containerfile
from crawfish.cache import CacheStats, CachingRuntime, cache_key
from crawfish.ccexport import (
    ClaudeCodeAgent,
    ClaudeCodeSkill,
    definition_to_cc_agent,
    export_claude_code,
    map_tools,
    model_alias,
)
from crawfish.config import (
    ModelsConfigError,
    ProfileConfig,
    ProjectManifest,
    ProjectPaths,
    load_manifest,
    load_models_config,
)
from crawfish.core import (
    BudgetExceeded,
    Cancelled,
    CancelToken,
    CostBudget,
    Flow,
    JSONValue,
    Node,
    NodeKind,
    Parameter,
    Policy,
    PolicyKind,
    RunContext,
    new_id,
    parameters_compatible,
)
from crawfish.cost import (
    Budget,
    BudgetState,
    CostEstimate,
    CostMeter,
    estimate_cost,
    spent_today,
)
from crawfish.definition import (
    AgentSpec,
    Coordination,
    Definition,
    DefinitionAssets,
    DefinitionLoadError,
    DefinitionRef,
    MarketplacePackage,
    MCPConnection,
    Prompt,
    TeamSpec,
    load_definition,
)
from crawfish.deploy import (
    DeployEntry,
    DeployRegistry,
    DeployStatus,
    Supervisor,
    deploy,
    stop,
)
from crawfish.discovery import Registry, UnitRef
from crawfish.doctor import DoctorFinding, DoctorReport, diagnose
from crawfish.emission import (
    EMISSION_SCHEMA_VERSION,
    REQUIRED_ATTRS,
    Emission,
    EmissionKind,
    emit,
    read_emissions,
)
from crawfish.engine import Engine, run_pipeline
from crawfish.escalate import abstention_threshold, extract_confidence
from crawfish.eval import (
    EvalCase,
    GoldenSet,
    LLMJudge,
    PromotionVerdict,
    capture_case,
    gate_against_baseline,
    grade_output,
    load_baseline,
    load_baseline_std,
    migrate_golden_set,
    promote_against_baseline,
    save_baseline,
    save_baseline_from_report,
    upconvert_case,
)
from crawfish.executor import (
    BatchExecutor,
    BatchRunResult,
    CycleError,
    DependencyGraph,
    ExecutionPlan,
    Roadmap,
)
from crawfish.inspector import RunReport, format_report, inspect_run, tail_events
from crawfish.jail import (
    BwrapJail,
    Denial,
    DenialKind,
    FakeJail,
    Jail,
    JailPath,
    JailResult,
    NoJail,
    PathMode,
    SandboxPolicy,
    SeatbeltJail,
    StaticOnlyError,
    TaintSet,
    UnsupportedPlatformError,
    emit_denials,
    registry_descriptors,
    rehydrate_registry,
    select_jail,
)
from crawfish.learning import (
    ExploreSchedule,
    ExploreStrategy,
    GraduationVerdict,
    IncompatibleStateError,
    LearningLoop,
    PromotionOutcome,
    RoleKnobs,
    ServingDecision,
    ServingLoop,
    StateDict,
    VersionRecord,
    load_state,
    state_dict,
)
from crawfish.ledger import ExecState, ExecutionLedger
from crawfish.manage import PipelineStatus, format_table, manage_list, restart_target
from crawfish.memory import Memory
from crawfish.metrics import (
    Benchmark,
    CalibrationReport,
    FieldExactMatch,
    Metric,
    NumericTolerance,
    Rubric,
    SchemaConformance,
    SetOverlap,
    StructuralMatch,
    calibrate,
    compare,
    confidence_threshold,
    field_exact_match,
    field_present,
    is_nonempty,
    is_regression,
    numeric_tolerance,
    output_number,
    schema_conformance,
    set_overlap,
    structural_match,
)
from crawfish.nodes import (
    Aggregator,
    ApprovalRequired,
    Classifier,
    Filter,
    GitHubPRSink,
    LinearSink,
    PullRequestSource,
    RepoSource,
    Router,
    Sink,
    Source,
    TargetMustBeStaticError,
    UnroutableLabelError,
    collect,
    concat,
    count,
    dedupe,
    definition_reducer,
    fan_in,
    fan_out,
    field_equals,
    field_matches,
    limit,
    title_contains,
)
from crawfish.observe import (
    ObserverEvent,
    ObserverSurface,
    RunInfo,
    Severity,
    parse_since,
)
from crawfish.observer import (
    CostSpike,
    FailureRateAbove,
    Observer,
    ObserverContext,
    Rule,
    StuckRun,
)
from crawfish.output import Output, WireError, check_wire, output_satisfies_inputs
from crawfish.provider import ModelsConfig, Provider, ProviderPolicy, resolve_model
from crawfish.refine import (
    PredicateStop,
    Refine,
    RefineResult,
    RubricThreshold,
    StopCondition,
    VerifierStop,
    feature_loop,
)
from crawfish.retry import ItemResult, ItemStatus, RetryPolicy
from crawfish.routing import (
    CostTier,
    RoutingDecision,
    RoutingPolicy,
    RoutingRule,
    agent_tier,
    route_decision,
    route_model,
    routing_emission,
)
from crawfish.run import InputBindingError, Run, RunStatus, RunSuspended
from crawfish.runtime import (
    AgentRuntime,
    CarryFull,
    CarryRecency,
    CarrySummary,
    CarryTypedFields,
    ClientProvider,
    ClientRuntime,
    CommandRuntime,
    Context,
    ContextCarryStrategy,
    ContextEntry,
    LocalHTTPProvider,
    LocalTransport,
    ManagedRuntime,
    MockProvider,
    MockRuntime,
    OpenAIChatRequest,
    ProviderFailover,
    ProviderRuntime,
    RecordReplayRuntime,
    RoutingRuntime,
    RunRequest,
    RunResult,
    RuntimeEvent,
    expand_candidates,
    get_runtime,
    resolve_carry_strategy,
)
from crawfish.sandbox import EgressBroker, EgressDenied, run_out_of_process
from crawfish.scaffold import scaffold_project
from crawfish.secrets import (
    GRANT_RECORD_KIND,
    ApprovalQueue,
    AutoApprovalQueue,
    AutoConsent,
    CallbackConsent,
    Capabilities,
    ConsentDecider,
    ConsentDeclined,
    ConsentRequest,
    DenyConsent,
    EgressTransport,
    Grant,
    GrantManifest,
    LeaseDenied,
    LeaseHandle,
    Outbound,
    PendingApproval,
    QueuedApprovalQueue,
    ScrubbingStore,
    SecretBroker,
    SecretManager,
    SecretRequest,
    brokered_mcp_config,
    consent_install,
    load_env,
    read_capabilities,
    redact,
    resolve_secret,
)
from crawfish.stability import (
    Stability,
    deprecated,
    experimental,
    is_breaking,
    stability_of,
    stable,
)
from crawfish.store import (
    CURRENT_SCHEMA_VERSION,
    Migration,
    SqliteStore,
    Store,
    StoreMigrationError,
)
from crawfish.testing import (
    INJECTION_INPUTS,
    STREAM_FIXTURES,
    TaintCase,
    assert_rubric,
    assert_snapshot,
    assert_taint_conformance,
    canned_transport,
    injection_tool_result,
    load_stream_fixture,
    replaying,
    run_fixtures,
    scoring_runtime,
    snapshot_match,
    taint_conformance_cases,
)
from crawfish.triggers import (
    Cron,
    CronSchedule,
    CronTrigger,
    Trigger,
    WebhookTrigger,
    verify_webhook,
)
from crawfish.tuner import (
    Candidate,
    ChainMutator,
    FewShotMutator,
    KnobDomain,
    KnobGridMutator,
    Mutation,
    Objective,
    ObjectiveForm,
    ObjectiveScore,
    PromptMutator,
    PromptVariantMutator,
    SearchStrategy,
    TrialResult,
    Tuner,
    TuneResult,
    TuneSpec,
    eval,
    guard_consequential,
    train,
    tune_spec_sha,
)
from crawfish.typesystem import TypeDef, TypeKind, TypeRegistry, default_registry
from crawfish.validation import (
    StructuralDiff,
    ValidationAction,
    ValidationError,
    ValidationFailure,
    structural_diff,
    validate_inputs,
    validate_output,
)
from crawfish.verifier import (
    GatedVerifier,
    Verdict,
    Verifier,
    VerifierStage,
)
from crawfish.versioning import Freezable, FrozenError, Version
from crawfish.visualize import (
    collect_emissions,
    dashboard_state,
    emission_dashboard_state,
    serve_dashboard,
    serve_emission_dashboard,
)
from crawfish.workflow import (
    Edge,
    Program,
    ProgramResult,
    Recurse,
    RecurseResult,
    UnboundedCycleError,
    UnboundedRecursionError,
    Workflow,
    branch,
    recurse,
)

__version__ = "0.2.0"

__all__ = [
    "__version__",
    # core
    "JSONValue",
    "new_id",
    "Flow",
    "Parameter",
    "NodeKind",
    "Node",
    "PolicyKind",
    "Policy",
    "parameters_compatible",
    "RunContext",
    "CostBudget",
    "CancelToken",
    "BudgetExceeded",
    "Cancelled",
    # type system
    "TypeDef",
    "TypeKind",
    "TypeRegistry",
    "default_registry",
    # versioning
    "Version",
    "FrozenError",
    "Freezable",
    # store
    "Store",
    "SqliteStore",
    "StoreMigrationError",
    "Migration",
    "CURRENT_SCHEMA_VERSION",
    # engine
    "Engine",
    "run_pipeline",
    # output
    "Output",
    "output_satisfies_inputs",
    "check_wire",
    "WireError",
    # definition
    "Definition",
    "AgentSpec",
    "TeamSpec",
    "Coordination",
    "Prompt",
    "DefinitionRef",
    "DefinitionAssets",
    "MarketplacePackage",
    "MCPConnection",
    "load_definition",
    "DefinitionLoadError",
    # runtime
    "AgentRuntime",
    "CommandRuntime",
    "MockRuntime",
    "ClientRuntime",
    "ManagedRuntime",
    "ProviderRuntime",
    "ProviderFailover",
    "expand_candidates",
    "MockProvider",
    "ClientProvider",
    "LocalHTTPProvider",
    "LocalTransport",
    "OpenAIChatRequest",
    "RoutingRuntime",
    "RecordReplayRuntime",
    "RunRequest",
    "RunResult",
    "RuntimeEvent",
    "get_runtime",
    # transferable typed Context artifact + carry strategies
    "Context",
    "ContextEntry",
    "ContextCarryStrategy",
    "CarryFull",
    "CarryRecency",
    "CarrySummary",
    "CarryTypedFields",
    "resolve_carry_strategy",
    # nodes (M2)
    "Source",
    "RepoSource",
    "PullRequestSource",
    "fan_out",
    "Sink",
    "LinearSink",
    "GitHubPRSink",
    "TargetMustBeStaticError",
    "ApprovalRequired",
    "Filter",
    "title_contains",
    "field_equals",
    "field_matches",
    "limit",
    "Memory",
    # run (M2)
    "Run",
    "RunStatus",
    "InputBindingError",
    "RunSuspended",
    # pipelines (M3)
    "Batch",
    "Task",
    "Anomaly",
    "Aggregator",
    "collect",
    "concat",
    "count",
    "dedupe",
    "definition_reducer",
    "fan_in",
    "Router",
    "Classifier",
    "UnroutableLabelError",
    "ArtifactRef",
    "ArtifactStore",
    "LocalArtifactStore",
    "offload_if_large",
    "DependencyGraph",
    "CycleError",
    "Roadmap",
    "ExecutionPlan",
    "BatchExecutor",
    "BatchRunResult",
    "ExecutionLedger",
    "LearningLoop",
    "PromotionOutcome",
    "VersionRecord",
    "ObserverEvent",
    "ObserverSurface",
    "RunInfo",
    "Severity",
    "parse_since",
    # operate / observe / integrate
    "DeployEntry",
    "DeployRegistry",
    "DeployStatus",
    "Supervisor",
    "deploy",
    "stop",
    "PipelineStatus",
    "manage_list",
    "format_table",
    "restart_target",
    "Observer",
    "ObserverContext",
    "Rule",
    "FailureRateAbove",
    "CostSpike",
    "StuckRun",
    # anomaly engine + auto-halt (CRA-190)
    "Response",
    "AnomalyRule",
    "CostSpikeRule",
    "FailureRateRule",
    "StuckRunRule",
    "EmissionFloodRule",
    "BudgetApproachingRule",
    "Firing",
    "AnomalyEngine",
    "read_and_guard",
    "dashboard_state",
    "serve_dashboard",
    "emission_dashboard_state",
    "collect_emissions",
    "serve_emission_dashboard",
    "ClaudeCodeAgent",
    "ClaudeCodeSkill",
    "definition_to_cc_agent",
    "export_claude_code",
    "map_tools",
    "model_alias",
    "ExecState",
    "RetryPolicy",
    "ItemResult",
    "ItemStatus",
    "Workflow",
    # measurement (M4)
    "Metric",
    "Rubric",
    "Benchmark",
    "output_number",
    "field_present",
    "is_nonempty",
    "confidence_threshold",
    "FieldExactMatch",
    "SetOverlap",
    "NumericTolerance",
    "SchemaConformance",
    "StructuralMatch",
    "field_exact_match",
    "set_overlap",
    "numeric_tolerance",
    "schema_conformance",
    "structural_match",
    "compare",
    "is_regression",
    "estimate_cost",
    "CostEstimate",
    "Budget",
    "BudgetState",
    "CostMeter",
    "spent_today",
    # cost & CPU optimization (CRA-182 — smart routing, replay caching, local models)
    "CostTier",
    "RoutingRule",
    "RoutingPolicy",
    "RoutingDecision",
    "agent_tier",
    "route_model",
    "route_decision",
    "routing_emission",
    "cache_key",
    "CacheStats",
    "CachingRuntime",
    "inspect_run",
    "tail_events",
    "format_report",
    "RunReport",
    # eval data lifecycle (M4)
    "EvalCase",
    "GoldenSet",
    "LLMJudge",
    "capture_case",
    "grade_output",
    "save_baseline",
    "load_baseline",
    "gate_against_baseline",
    "upconvert_case",
    "migrate_golden_set",
    # authoring / packaging / ship (M5)
    "Registry",
    "UnitRef",
    "ProfileConfig",
    "ProjectManifest",
    "ProjectPaths",
    "load_manifest",
    "load_models_config",
    "ModelsConfigError",
    "DoctorFinding",
    "DoctorReport",
    "diagnose",
    "Cron",
    "CronSchedule",
    "scaffold_project",
    "resolve_secret",
    "load_env",
    "SecretManager",
    "ScrubbingStore",
    "redact",
    "read_capabilities",
    "Capabilities",
    "ConsentRequest",
    "ConsentDecider",
    "AutoConsent",
    "DenyConsent",
    "CallbackConsent",
    "GrantManifest",
    "ConsentDeclined",
    "consent_install",
    "GRANT_RECORD_KIND",
    "snapshot_match",
    "assert_snapshot",
    "run_fixtures",
    "assert_rubric",
    "replaying",
    # CRA-185 shared determinism harness
    "STREAM_FIXTURES",
    "canned_transport",
    "load_stream_fixture",
    "INJECTION_INPUTS",
    "injection_tool_result",
    "scoring_runtime",
    "TaintCase",
    "taint_conformance_cases",
    "assert_taint_conformance",
    "generate_containerfile",
    "plan_build",
    "write_containerfile",
    "BuildPlan",
    "Trigger",
    "CronTrigger",
    "WebhookTrigger",
    "verify_webhook",
    "Stability",
    "stable",
    "experimental",
    "deprecated",
    "stability_of",
    "is_breaking",
    "EgressBroker",
    "EgressDenied",
    "run_out_of_process",
    # Phase 2 — sandboxed pipelines (CRA-179, the Jail abstraction, ADR 0016)
    "Jail",
    "FakeJail",
    "NoJail",
    "BwrapJail",
    "SeatbeltJail",
    "JailPath",
    "PathMode",
    "JailResult",
    "Denial",
    "DenialKind",
    "SandboxPolicy",
    "TaintSet",
    "StaticOnlyError",
    "UnsupportedPlatformError",
    "select_jail",
    "registry_descriptors",
    "rehydrate_registry",
    "emit_denials",
    # Phase 2 contracts (CRA-184 interface freeze)
    "Emission",
    "EmissionKind",
    "REQUIRED_ATTRS",
    "EMISSION_SCHEMA_VERSION",
    "emit",
    "read_emissions",
    "ValidationFailure",
    "ValidationAction",
    "ValidationError",
    "StructuralDiff",
    "validate_output",
    "validate_inputs",
    "structural_diff",
    "Provider",
    "ProviderPolicy",
    "ModelsConfig",
    "resolve_model",
    "Grant",
    # CRA-178 — secret schema + sidecar broker (egress-mediated injection)
    "SecretRequest",
    "LeaseHandle",
    "LeaseDenied",
    "Outbound",
    "EgressTransport",
    "PendingApproval",
    "ApprovalQueue",
    "AutoApprovalQueue",
    "QueuedApprovalQueue",
    "SecretBroker",
    "brokered_mcp_config",
    # the Tuner (CRA-176 — deterministic in-house search, ADR 0015)
    "Mutation",
    "Candidate",
    "PromptMutator",
    "PromptVariantMutator",
    "KnobGridMutator",
    "FewShotMutator",
    "ChainMutator",
    "SearchStrategy",
    "TrialResult",
    "TuneResult",
    "Tuner",
    # the Verifier (CRA-203 — CL-2, the gated external-signal critic)
    "Verifier",
    "GatedVerifier",
    "Verdict",
    "VerifierStage",
    # Refine — the verifier-gated, bounded, durable iterate-until-goal loop
    # (CRA-202 CL-1 + CRA-204 CL-4)
    "Refine",
    "RefineResult",
    "StopCondition",
    "RubricThreshold",
    "PredicateStop",
    "VerifierStop",
    "feature_loop",
    # Composition surface — cyclic Program, runnable Router branch, bounded recurse
    # (CRA-205/206/207/208)
    "branch",
    "Program",
    "Edge",
    "ProgramResult",
    "UnboundedCycleError",
    "recurse",
    "Recurse",
    "RecurseResult",
    "UnboundedRecursionError",
    # Tunable ML library — two-axis mode (train/eval) + tunable knobs + cost-regularized objective
    # (CRA-209, CRA-213)
    "KnobDomain",
    "TuneSpec",
    "tune_spec_sha",
    "train",
    "eval",
    "guard_consequential",
    "Objective",
    "ObjectiveForm",
    "ObjectiveScore",
    # Calibration — variance / ECE / abstention (CRA-211)
    "calibrate",
    "CalibrationReport",
    "extract_confidence",
    "abstention_threshold",
    # Variance-aware promotion gate (CRA-212)
    "promote_against_baseline",
    "PromotionVerdict",
    "load_baseline_std",
    "save_baseline_from_report",
    # state_dict transfer + explore-rate serving loop (CRA-210, CRA-214)
    "state_dict",
    "load_state",
    "StateDict",
    "RoleKnobs",
    "IncompatibleStateError",
    "ServingLoop",
    "ServingDecision",
    "ExploreSchedule",
    "ExploreStrategy",
    "GraduationVerdict",
]
